name: auto-merge

on:
  push:
    branches:
      - DWM

jobs:
  run-ci:
    uses: ./.github/workflows/ci-laravel.yml
    secrets: inherit

  merge:
    needs: run-ci
    runs-on: ubuntu-latest
    if: always() && needs.run-ci.result == 'success'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch and merge branches
        run: |
          git fetch origin
          git checkout main
          git merge origin/DWM --no-ff -m "auto-merge"
          git push origin main
