name: Auto Merge DWM into main

on:
  workflow_run:
    workflows: ["CI Laravel"]
    types:
      - completed

jobs:
  merge:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'DWM'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "MarcA"
          git config --global user.email "marcarbiolrams@gmail.com"

      - name: Merge DWM into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/DWM --no-ff -m "Auto-merge DWM -> main"
          git push origin main
